# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-15 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerid', models.IntegerField(default=1)),
                ('image', models.CharField(max_length=2001)),
            ],
            options={
                'db_table': 'dy_wheel',
            },
        ),
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postpeid', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=32)),
                ('image', models.CharField(max_length=200)),
                ('duration', models.IntegerField(default=1)),
                ('app_fu_title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'dy_movies',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('u_email', models.CharField(max_length=32, unique=True)),
                ('u_icon', models.ImageField(upload_to='icons')),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
